[2023-10-12T16:38:03.338+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gx.create_table_pg manual__2023-10-12T16:37:56.816476+00:00 [queued]>
[2023-10-12T16:38:03.347+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gx.create_table_pg manual__2023-10-12T16:37:56.816476+00:00 [queued]>
[2023-10-12T16:38:03.348+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-12T16:38:03.362+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_table_pg> on 2023-10-12 16:37:56.816476+00:00
[2023-10-12T16:38:03.370+0000] {standard_task_runner.py:57} INFO - Started process 186 to run task
[2023-10-12T16:38:03.376+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gx', 'create_table_pg', 'manual__2023-10-12T16:37:56.816476+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/gx.py', '--cfg-path', '/tmp/tmpcagvw_r0']
[2023-10-12T16:38:03.378+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask create_table_pg
[2023-10-12T16:38:03.440+0000] {task_command.py:415} INFO - Running <TaskInstance: gx.create_table_pg manual__2023-10-12T16:37:56.816476+00:00 [running]> on host fda3e6cd0d41
[2023-10-12T16:38:03.530+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gx' AIRFLOW_CTX_TASK_ID='create_table_pg' AIRFLOW_CTX_EXECUTION_DATE='2023-10-12T16:37:56.816476+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-12T16:37:56.816476+00:00'
[2023-10-12T16:38:03.531+0000] {sql.py:274} INFO - Executing: 
            CREATE TABLE strawberries (
                id VARCHAR(10) PRIMARY KEY,
                name VARCHAR(100),
                amount INT
            );

            INSERT INTO strawberries (id, name, amount)
            VALUES ('001', 'Strawberry Order 1', 10),
                ('002', 'Strawberry Order 2', 5),
                ('003', 'Strawberry Order 3', 8),
                ('004', 'Strawberry Order 4', 3),
                ('005', 'Strawberry Order 5', 12);
            
[2023-10-12T16:38:03.541+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-10-12T16:38:03.555+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-10-12T16:38:03.556+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.17.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2023-10-12T16:38:03.565+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gx, task_id=create_table_pg, execution_date=20231012T163756, start_date=20231012T163803, end_date=20231012T163803
[2023-10-12T16:38:03.577+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task create_table_pg (connection to server at "172.17.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 186)
[2023-10-12T16:38:03.589+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-12T16:38:03.611+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
