[2023-10-11T04:32:30.376+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker.system_maintenance_task manual__2023-10-11T04:32:29.468411+00:00 [queued]>
[2023-10-11T04:32:30.380+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker.system_maintenance_task manual__2023-10-11T04:32:29.468411+00:00 [queued]>
[2023-10-11T04:32:30.380+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-11T04:32:30.387+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): system_maintenance_task> on 2023-10-11 04:32:29.468411+00:00
[2023-10-11T04:32:30.391+0000] {standard_task_runner.py:57} INFO - Started process 197 to run task
[2023-10-11T04:32:30.394+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'docker', 'system_maintenance_task', 'manual__2023-10-11T04:32:29.468411+00:00', '--job-id', '1403', '--raw', '--subdir', 'DAGS_FOLDER/docker.py', '--cfg-path', '/tmp/tmpushmeqoc']
[2023-10-11T04:32:30.394+0000] {standard_task_runner.py:85} INFO - Job 1403: Subtask system_maintenance_task
[2023-10-11T04:32:30.424+0000] {task_command.py:415} INFO - Running <TaskInstance: docker.system_maintenance_task manual__2023-10-11T04:32:29.468411+00:00 [running]> on host 1e16ce4c9e98
[2023-10-11T04:32:30.461+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='docker' AIRFLOW_CTX_TASK_ID='system_maintenance_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-11T04:32:29.468411+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-11T04:32:29.468411+00:00'
[2023-10-11T04:32:30.462+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-11T04:32:30.462+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'apt-get update && apt-get upgrade -y']
[2023-10-11T04:32:30.475+0000] {subprocess.py:86} INFO - Output:
[2023-10-11T04:32:30.746+0000] {subprocess.py:93} INFO - Reading package lists...
[2023-10-11T04:32:30.754+0000] {subprocess.py:93} INFO - E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
[2023-10-11T04:32:30.755+0000] {subprocess.py:93} INFO - E: Unable to lock directory /var/lib/apt/lists/
[2023-10-11T04:32:30.756+0000] {subprocess.py:97} INFO - Command exited with return code 100
[2023-10-11T04:32:30.763+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 100.
[2023-10-11T04:32:30.765+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=docker, task_id=system_maintenance_task, execution_date=20231011T043229, start_date=20231011T043230, end_date=20231011T043230
[2023-10-11T04:32:30.772+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1403 for task system_maintenance_task (Bash command failed. The command returned a non-zero exit code 100.; 197)
[2023-10-11T04:32:30.806+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-11T04:32:30.822+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
