[2023-10-10T17:59:47.187+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gx.create_table_pg manual__2023-10-10T17:59:43.375806+00:00 [queued]>
[2023-10-10T17:59:47.191+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gx.create_table_pg manual__2023-10-10T17:59:43.375806+00:00 [queued]>
[2023-10-10T17:59:47.191+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T17:59:47.197+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_table_pg> on 2023-10-10 17:59:43.375806+00:00
[2023-10-10T17:59:47.205+0000] {standard_task_runner.py:57} INFO - Started process 174 to run task
[2023-10-10T17:59:47.208+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gx', 'create_table_pg', 'manual__2023-10-10T17:59:43.375806+00:00', '--job-id', '1370', '--raw', '--subdir', 'DAGS_FOLDER/gx.py', '--cfg-path', '/tmp/tmp1giwb4tw']
[2023-10-10T17:59:47.208+0000] {standard_task_runner.py:85} INFO - Job 1370: Subtask create_table_pg
[2023-10-10T17:59:47.233+0000] {task_command.py:415} INFO - Running <TaskInstance: gx.create_table_pg manual__2023-10-10T17:59:43.375806+00:00 [running]> on host 08721473190e
[2023-10-10T17:59:47.271+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gx' AIRFLOW_CTX_TASK_ID='create_table_pg' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T17:59:43.375806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-10T17:59:43.375806+00:00'
[2023-10-10T17:59:47.272+0000] {sql.py:274} INFO - Executing: 
            CREATE TABLE strawberries (
                id VARCHAR(10) PRIMARY KEY,
                name VARCHAR(100),
                amount INT
            );

            INSERT INTO strawberries (id, name, amount)
            VALUES ('001', 'Strawberry Order 1', 10),
                ('002', 'Strawberry Order 2', 5),
                ('003', 'Strawberry Order 3', 8),
                ('004', 'Strawberry Order 4', 3),
                ('005', 'Strawberry Order 5', 12);
            
[2023-10-10T17:59:47.276+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-10-10T17:59:47.283+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-10-10T17:59:47.285+0000] {sql.py:418} INFO - Running statement: 
            CREATE TABLE strawberries (
                id VARCHAR(10) PRIMARY KEY,
                name VARCHAR(100),
                amount INT
            );

            INSERT INTO strawberries (id, name, amount)
            VALUES ('001', 'Strawberry Order 1', 10),
                ('002', 'Strawberry Order 2', 5),
                ('003', 'Strawberry Order 3', 8),
                ('004', 'Strawberry Order 4', 3),
                ('005', 'Strawberry Order 5', 12);
            , parameters: None
[2023-10-10T17:59:47.286+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "strawberries" already exists

[2023-10-10T17:59:47.290+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gx, task_id=create_table_pg, execution_date=20231010T175943, start_date=20231010T175947, end_date=20231010T175947
[2023-10-10T17:59:47.296+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1370 for task create_table_pg (relation "strawberries" already exists
; 174)
[2023-10-10T17:59:47.339+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T17:59:47.354+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
